force-app/main/default/objects/CustomChatterPost__mdt/CustomChatterPost__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata used to create custom chatter posts</description>
    <label>CustomChatterPost</label>
    <pluralLabel>CustomChatterPosts</pluralLabel>
</CustomObject>

force-app/main/default/objects/CustomChatterPost__mdt/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/TradeEvent__e/TradeEvent__e.object-meta.xml
<CustomObject>
    <label>TradeEvent</label>
    <pluralLabel>TradeEvents</pluralLabel>
</CustomObject>

force-app/main/default/classes/FeedItemHandler.cls
public with sharing class FeedItemHandler {

    public static void createFeedItems(List<TradeEvent__e> feedItemsEvent){
        List<FeedItem> feedItems = new List<FeedItem>();
        System.debug(feedItemsEvent);

        //Get all users from particular queue
        Set<Id> groupMemberIds = GroupMemberSelector.getAllMemberIdsByQueueName('Trade reviewers');

        //Get custom metadata
        CustomChatterPost__mdt customChatterPost = CustomChatterPost__mdt.getInstance('TradeCreated');
        String messageBody = customChatterPost.Body__c; //Add os parametros na mensagem

        //criar um feed Item pra cada event
        for(TradeEvent__e event : feedItemsEvent){
            FeedItem feedItem = new FeedItem();
            feedItem.Body = messageBody;

            for(Id userId : groupMemberIds){
                feedItem.ParentId = userId;
            }
            feedItems.add(feedItem);
        }

        insert feedItems; //Add service pra fazer insert
    }
}