force-app/main/default/objects/TradeEvent__e/TradeEvent__e.object-meta.xml
<CustomObject>
    <label>TradeEvent</label>
    <pluralLabel>TradeEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/TradeEvent__e/fields/BuyAmount__c.field-meta.xml
<CustomField>
    <fullName>BuyAmount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TradeEvent__e/fields/BuyCurrency__c.field-meta.xml
<CustomField>
    <fullName>BuyCurrency__c</fullName>
    <label>Buy Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TradeEvent__e/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TradeEvent__e/fields/SellAmount__c.field-meta.xml
<CustomField>
    <fullName>SellAmount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TradeEvent__e/fields/SellCurrency__c.field-meta.xml
<CustomField>
    <fullName>SellCurrency__c</fullName>
    <label>Sell Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FeedItemHandlerTest.cls
//all test classes were made in the 'standard' way but 
//the main idea is to mock/stub all records to improve the tests
@IsTest
public with sharing class FeedItemHandlerTest {
 
    @IsTest
    public static void createFeedItems_withValidEvent_shouldCreateRecord(){

        List<TradeEvent__e> tradeEvents = new List<TradeEvent__e>();
        tradeEvents.add(createTradeEvent());
        FeedItemHandler.createFeedItems(tradeEvents);

        FeedItem feedItem = [Select Id from FeedItem];
        System.assertEquals(true, feedItem!= null, 'FeedItem record should be created');
    }

    private static TradeEvent__e createTradeEvent(){

        TradeEvent__e tradeEvent = new TradeEvent__e(
            BuyAmount__c = 3000,
            BuyCurrency__c = 'EUR',
            Rate__c = 1.5,
            SellAmount__c = 1000,
            SellCurrency__c = 'BRL'
        );
        return tradeEvent;
    }
}