force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/BuyAmount__c.field-meta.xml
<CustomField>
    <fullName>BuyAmount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/BuyCurrency__c.field-meta.xml
<CustomField>
    <fullName>BuyCurrency__c</fullName>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellAmount__c.field-meta.xml
<CustomField>
    <fullName>SellAmount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellCurrency__c.field-meta.xml
<CustomField>
    <fullName>SellCurrency__c</fullName>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
@IsTest
public with sharing class TestDataFactory {

    public static User createUserAdmin(){

        User user = new User();
        user.FirstName = 'Teste Name';
        user.LastName = 'Last Name';
        user.Username = 'ebury@teste.Mariana';
        user.Email = 'ebury@teste.Mariana';
        user.Alias = 'alias';
        user.ProfileId = getProfile().Id;
        user.TimeZoneSidKey = 'Europe/Lisbon';
        user.LocaleSidKey = 'pt_BR';
        user.EmailEncodingKey = 'UTF-8';
        user.LanguageLocaleKey = 'en_US';

        return user;
    }

    public static Profile getProfile(){
        return [Select Id from Profile Where Name='System Administrator' Limit 1];
    }

    public static Group createQueue(String groupName){

        Group queue = new Group();
        queue.Name = groupName;
        queue.Type = 'Queue';

        return queue;
    }

    public static GroupMember createGroupMember(Id userId, Id groupId){

        GroupMember groupMember = new GroupMember();
        groupMember.GroupId = groupId;
        groupMember.UserOrGroupId = userId;

        return GroupMember;
    }

    public static Trade__c createTrade(){
        Trade__c trade = new Trade__c();
        trade.Rate__c = 1;
        trade.SellCurrency__c = 'BRL';
        trade.BuyCurrency__c = 'EUR';
        trade.SellAmount__c = 1000;
        trade.BuyAmount__c = 2000;

        return trade;
    }

    public static TRD_TradeAppController.TradeInfo createTradeInfo(){

        TRD_TradeAppController.TradeInfo tradeInfo = new TRD_TradeAppController.TradeInfo();
        tradeInfo.buyAmount = 100;
        tradeInfo.buyCurrency = 'BRL';
        tradeInfo.rate = 1;
        tradeInfo.sellAmount = 10000;
        tradeInfo.sellCurrency = 'EUR';

        return tradeInfo;
    }
}