force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/BuyAmount__c.field-meta.xml
<CustomField>
    <fullName>BuyAmount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/BuyCurrency__c.field-meta.xml
<CustomField>
    <fullName>BuyCurrency__c</fullName>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellAmount__c.field-meta.xml
<CustomField>
    <fullName>SellAmount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellCurrency__c.field-meta.xml
<CustomField>
    <fullName>SellCurrency__c</fullName>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TRD_TradeAppController.cls
public with sharing class TRD_TradeAppController {

    @AuraEnabled
    public static List<Trade__c> getAllTrades(){
        try {
            return TRD_TradeSelector.getAllOrderedByCreatedDate(); //Treat to not return Id to LWC
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled //Parece pronto
    public static List<String> getCurrencies(){

        SObjectType tradeObject = Trade__c.SObjectType;
        Schema.SObjectField buyCurrencyField = Trade__c.BuyCurrency__c;

        List<String> currencyList = PicklistUtils.getPicklistValuesList(tradeObject, buyCurrencyField);

        return currencyList;
    }

    @AuraEnabled //Parece Pronto
    public static String getRateAndAmount(String amount, String fromCurrency, String toCurrency){
        
        TRD_FixerApiModel returnedConversion = TRD_CalloutFixerApi.getConversion(amount, fromCurrency, toCurrency);

        TradeInfo tradeToReturn = new TradeInfo();
        tradeToReturn.buyAmount = returnedConversion.result;
        tradeToReturn.rate = returnedConversion.Info.rate;

        return JSON.serialize(tradeToReturn);
    }

    @AuraEnabled //Add Model? 
    public static void createTrade(String trade){

            TradeInfo tradeToCreate = (TradeInfo)JSON.deserialize(trade, TradeInfo.class);
            List<Trade__c> trades = new List<Trade__c>();

            Trade__c tradeRecord = new Trade__c(); //add a model class to do it
            tradeRecord.SellCurrency__c = tradeToCreate.sellCurrency;
            tradeRecord.BuyCurrency__c = tradeToCreate.buyCurrency;
            tradeRecord.BuyAmount__c = tradeToCreate.buyAmount;
            tradeRecord.SellAmount__c = tradeToCreate.sellAmount;
            tradeRecord.Rate__c = tradeToCreate.rate;
            
            TRD_TradeService.createTrade(tradeRecord);
            trades.add(tradeRecord);

            //Criar o Event de FeedItem 
            TRD_TradeHandler.publishTradeEvent(trades);
    }

    private class TradeInfo{

        String sellCurrency;
        String buyCurrency;
        Decimal buyAmount;
        Decimal sellAmount;
        Decimal rate;

    }
}